services:
  database:
    container_name: sqs_database
    image: postgres:16.3
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
    