services:
  database:
    container_name: sqs_database
    image: postgres:16.3
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
    
  rbmq:
    container_name: rbmq_contanier
    image: rabbitmq:4.0
    restart: no
    env_file: .env
    ports: 
      - 5672:5672
